#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 使用 Simplex I2S 模式（麦克风和扬声器分开）
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

// INMP441 I2S 麦克风 (GPIO1=BCLK, GPIO2=WS, GPIO3=DIN)
#define AUDIO_I2S_MIC_GPIO_SCK   GPIO_NUM_1
#define AUDIO_I2S_MIC_GPIO_WS    GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_DIN   GPIO_NUM_3

// MAX98357A I2S 扬声器 (GPIO4=BCLK, GPIO15=LRCLK, GPIO11=DIN)
#define AUDIO_I2S_SPK_GPIO_BCLK  GPIO_NUM_4
#define AUDIO_I2S_SPK_GPIO_LRCK  GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_DOUT  GPIO_NUM_11

#else

// Duplex 模式 (未使用)
#define AUDIO_I2S_GPIO_WS  GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_3
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_11

#endif

// 按键定义
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_14
#define ASR_BUTTON_GPIO         GPIO_NUM_21
#define USER_BUTTON_GPIO        GPIO_NUM_0

// ST7789 LCD 屏幕引脚 (T-Display-S3 标准版)
#define DISPLAY_CS_PIN         GPIO_NUM_6
#define DISPLAY_DC_PIN         GPIO_NUM_7
#define DISPLAY_RST_PIN        GPIO_NUM_5
#define DISPLAY_MOSI_PIN       GPIO_NUM_9
#define DISPLAY_MISO_PIN       GPIO_NUM_8
#define DISPLAY_CLK_PIN        GPIO_NUM_10
#define DISPLAY_BL_PIN         GPIO_NUM_38

// ST7789 170x320 显示参数
#ifdef CONFIG_LCD_ST7789_170X320
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   170
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  35
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

// LED
#define BUILTIN_LED_GPIO        GPIO_NUM_40

#endif
